version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "reddit-pipeline"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jad1xu89e69r"
s3_prefix = "reddit-pipeline"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
