AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for reddit_pipeline

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        REDDIT_APP_NAME: MyDataPipelineApp
        REDDIT_USERNAME: Impressive_Being_607
        REDDIT_APP_SECRET: '{{resolve:secretsmanager:reddit_secrets:SecretString:REDDIT_APP_SECRET}}'
        REDDIT_APP_ID: '{{resolve:secretsmanager:reddit_secrets:SecretString:REDDIT_APP_ID}}'

Resources:
  SubredditStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: subreddit-stream-function
      CodeUri: app/lambdas/
      Handler: subreddit_stream.lambda_handler
      Runtime: python3.8
      Events:
        SubredditStream:
          Type: Api
          Properties:
            Path: /subreddit-stream
            Method: get
        ScheduledEvent:
          Name: Every5min
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)         
  SubredditStreamQueue:
    Type: AWS::SQS::Queue
    Description: Process messages from subreddit-stream-function
    Properties:
      QueueName: subreddit-stream-queue
      FifoQueue: true

Outputs:
  SubredditStreamApi:
    Description: "API Gateway endpoint URL for Prod stage for SubredditStream function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subreddit-stream/"
  SubredditStreamFunction:
    Description: "SubredditStream Lambda Function ARN"
    Value: !GetAtt SubredditStreamFunction.Arn
  SubredditStreamFunctionIamRole:
    Description: "Implicit IAM Role created for SubredditStream function"
    Value: !GetAtt SubredditStreamFunctionRole.Arn
  SubredditStreamQueueURL: 
    Description: "URL of SubredditStreamQueue"
    Value: 
      Ref: "SubredditStreamQueue"
  SubredditStreamQueueARN: 
    Description: "ARN of SubredditStreamQueue"
    Value: 
      Fn::GetAtt: 
        - "SubredditStreamQueue"
        - "Arn"
  SubredditStreamQueueName: 
    Description: "Name of new SubredditStreamQueue"
    Value: 
      Fn::GetAtt: 
        - "SubredditStreamQueue"
        - "QueueName"