name: AWS SAM Pipeline
on:
  push:
    branches:
      - 'main'
    pull_request:
jobs:
  build-sam-template:
    runs-on: ubuntu-latest
    environment: reddit-pipeline
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # sam build 
      - run: sam build --use-container
      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
