name: AWS SAM Workflow
on:
  push:
    branches:
      - 'main'
    pull_request:
jobs:
  build-sam-template:
    runs-on: ubuntu-latest
    environment: reddit-pipeline
    steps:
      # pre-build installations
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # sam build 
      - run: sam build --use-container
      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name reddit-pipeline --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-jad1xu89e69r --capabilities CAPABILITY_NAMED_IAM --region us-east-2
  run-db-migrations:
    runs-on: ubuntu-latest
    environment: reddit-pipeline
    steps:
      # pre-build installations
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv psycopg2-binary alembic
      # authorize default security group to allow inbound access from GHA IP
      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Add GitHub Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name default --cidr ${{ steps.ip.outputs.ipv4 }}/32    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
      # run database migrations
      - run: alembic upgrade head
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
      # remove GHA IP from security group
      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name default --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
        if: always() # run even if previous step fails